/**
 * Analysis Display Component
 * Shows document analysis results in a structured format
 * Now includes advanced AI features: custom summaries, information extraction, and document comparison
 */

import React, { useState } from 'react';
import {
    FaFileAlt,
    FaClock,
    FaBook,
    FaLightbulb,
    FaCheckCircle,
    FaSmile,
    FaTags,
    FaEnvelope,
    FaDownload,
    FaCopy,
    FaBalanceScale
} from 'react-icons/fa';
import { toast } from 'react-toastify';
import ApiService from '../services/api';
import AIApiService from '../services/aiApi';
import ComparisonModal from './ComparisonModal';

const AnalysisDisplay = ({ analysis, onSendEmail }) => {
    // Email state
    const [emailInput, setEmailInput] = useState('');
    const [isSendingEmail, setIsSendingEmail] = useState(false);

    // Advanced AI features state
    const [showAdvancedFeatures, setShowAdvancedFeatures] = useState(false);
    const [extractionType, setExtractionType] = useState('dates');
    const [extractedInfo, setExtractedInfo] = useState(null);
    const [isExtracting, setIsExtracting] = useState(false);
    const [summaryLength, setSummaryLength] = useState('medium');
    const [customSummary, setCustomSummary] = useState(null);
    const [isGeneratingSummary, setIsGeneratingSummary] = useState(false);

    // Comparison modal state
    const [showComparisonModal, setShowComparisonModal] = useState(false);

    if (!analysis) return null;

    const { fileName, metadata, analysis: analysisData, id } = analysis;

    const getSentimentColor = (sentiment) => {
        const colors = {
            positive: '#10b981',
            neutral: '#f59e0b',
            negative: '#ef4444'
        };
        return colors[sentiment?.toLowerCase()] || colors.neutral;
    };

    const getSentimentIcon = (sentiment) => {
        return <FaSmile style={{ color: getSentimentColor(sentiment) }} />;
    };

    const handleSendEmail = async () => {
        if (!emailInput || !emailInput.includes('@')) {
            toast.error('Please enter a valid email address');
            return;
        }

        setIsSendingEmail(true);
        try {
            await ApiService.resendEmail(id, emailInput);
            toast.success('Email sent successfully!');
            setEmailInput('');
        } catch (error) {
            toast.error('Failed to send email');
            console.error(error);
        } finally {
            setIsSendingEmail(false);
        }
    };

    const handleCopyToClipboard = (text) => {
        navigator.clipboard.writeText(text);
        toast.success('Copied to clipboard!');
    };

    const handleDownloadReport = () => {
        const reportContent = `
DocuMind AI - Analysis Report
================================

Document: ${fileName}
Analyzed: ${new Date(analysis.uploadedAt).toLocaleString()}

METADATA
--------
Word Count: ${metadata.wordCount}
Reading Time: ${metadata.readingTime}
File Size: ${(metadata.fileSize / 1024).toFixed(2)} KB

EXECUTIVE SUMMARY
-----------------
${analysisData.summary}

KEY POINTS
----------
${analysisData.keyPoints?.map((point, i) => `${i + 1}. ${point}`).join('\n')}

${analysisData.actionItems?.length > 0 ? `
ACTION ITEMS
------------
${analysisData.actionItems.map((item, i) => `${i + 1}. ${item}`).join('\n')}
` : ''}

SENTIMENT ANALYSIS
------------------
${analysisData.sentiment}

${analysisData.topics?.length > 0 ? `
TOPICS
------
${analysisData.topics.join(', ')}
` : ''}

${analysisData.entities ? `
KEY ENTITIES
------------
${Object.entries(analysisData.entities).map(([type, items]) =>
            items?.length > 0 ? `${type.charAt(0).toUpperCase() + type.slice(1)}: ${items.join(', ')}` : ''
        ).filter(Boolean).join('\n')}
` : ''}

---
Generated by DocuMind AI
    `.trim();

        const blob = new Blob([reportContent], { type: 'text/plain' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${fileName.replace(/\.[^/.]+$/, '')}_analysis.txt`;
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(url);
        document.body.removeChild(a);
        toast.success('Report downloaded!');
    };

    // Advanced AI feature handlers
    const handleExtractInfo = async () => {
        setIsExtracting(true);
        setExtractedInfo(null);
        try {
            const response = await AIApiService.extractInformation(id, extractionType);
            setExtractedInfo(response.data);
            toast.success(`Extracted ${extractionType} successfully!`);
        } catch (error) {
            toast.error('Failed to extract information');
            console.error(error);
        } finally {
            setIsExtracting(false);
        }
    };

    const handleGenerateCustomSummary = async () => {
        setIsGeneratingSummary(true);
        setCustomSummary(null);
        try {
            const response = await AIApiService.generateSummary(id, summaryLength);
            setCustomSummary(response.data);
            toast.success('Summary generated!');
        } catch (error) {
            toast.error('Failed to generate summary');
            console.error(error);
        } finally {
            setIsGeneratingSummary(false);
        }
    };

    return (
        <div className="analysis-display">
            {/* Header Section */}
            <div className="analysis-header">
                <div className="document-info">
                    <FaFileAlt className="doc-icon" />
                    <div>
                        <h2 className="document-name">{fileName}</h2>
                        <p className="upload-date">
                            Analyzed on {new Date(analysis.uploadedAt).toLocaleString()}
                        </p>
                    </div>
                </div>

                <div className="action-buttons">
                    <button
                        className="btn-icon"
                        onClick={handleDownloadReport}
                        title="Download Report"
                    >
                        <FaDownload />
                    </button>
                    <button
                        className="btn-icon"
                        onClick={() => handleCopyToClipboard(analysisData.summary)}
                        title="Copy Summary"
                    >
                        <FaCopy />
                    </button>
                    <button
                        className="btn-icon"
                        onClick={() => setShowComparisonModal(true)}
                        title="Compare with Another Document"
                    >
                        <FaBalanceScale />
                    </button>
                </div>
            </div>

            {/* Stats Cards */}
            <div className="stats-grid">
                <div className="stat-card">
                    <FaBook className="stat-icon" />
                    <div className="stat-content">
                        <p className="stat-value">{metadata.wordCount?.toLocaleString()}</p>
                        <p className="stat-label">Words</p>
                    </div>
                </div>

                <div className="stat-card">
                    <FaClock className="stat-icon" />
                    <div className="stat-content">
                        <p className="stat-value">{metadata.readingTime}</p>
                        <p className="stat-label">Reading Time</p>
                    </div>
                </div>

                <div className="stat-card">
                    <FaLightbulb className="stat-icon" />
                    <div className="stat-content">
                        <p className="stat-value">{analysisData.keyPoints?.length || 0}</p>
                        <p className="stat-label">Key Points</p>
                    </div>
                </div>

                <div className="stat-card">
                    {getSentimentIcon(analysisData.sentiment)}
                    <div className="stat-content">
                        <p className="stat-value">{analysisData.sentiment || 'Neutral'}</p>
                        <p className="stat-label">Sentiment</p>
                    </div>
                </div>
            </div>

            {/* Executive Summary */}
            <div className="analysis-section">
                <div className="section-header">
                    <FaFileAlt className="section-icon" />
                    <h3>Executive Summary</h3>
                </div>
                <div className="section-content">
                    <p className="summary-text">{analysisData.summary}</p>
                </div>
            </div>

            {/* Key Points */}
            {analysisData.keyPoints && analysisData.keyPoints.length > 0 && (
                <div className="analysis-section">
                    <div className="section-header">
                        <FaLightbulb className="section-icon" />
                        <h3>Key Points</h3>
                    </div>
                    <div className="section-content">
                        <ul className="key-points-list">
                            {analysisData.keyPoints.map((point, index) => (
                                <li key={index} className="key-point-item">
                                    <span className="point-number">{index + 1}</span>
                                    <span className="point-text">{point}</span>
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>
            )}

            {/* Action Items */}
            {analysisData.actionItems && analysisData.actionItems.length > 0 && (
                <div className="analysis-section">
                    <div className="section-header">
                        <FaCheckCircle className="section-icon" />
                        <h3>Action Items</h3>
                    </div>
                    <div className="section-content">
                        <ul className="action-items-list">
                            {analysisData.actionItems.map((item, index) => (
                                <li key={index} className="action-item">
                                    <FaCheckCircle className="check-icon" />
                                    {item}
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>
            )}

            {/* Topics */}
            {analysisData.topics && analysisData.topics.length > 0 && (
                <div className="analysis-section">
                    <div className="section-header">
                        <FaTags className="section-icon" />
                        <h3>Topics & Categories</h3>
                    </div>
                    <div className="section-content">
                        <div className="topics-container">
                            {analysisData.topics.map((topic, index) => (
                                <span key={index} className="topic-tag">{topic}</span>
                            ))}
                        </div>
                    </div>
                </div>
            )}

            {/* Key Entities */}
            {analysisData.entities && Object.keys(analysisData.entities).length > 0 && (
                <div className="analysis-section">
                    <div className="section-header">
                        <FaTags className="section-icon" />
                        <h3>Key Entities</h3>
                    </div>
                    <div className="section-content">
                        {Object.entries(analysisData.entities).map(([type, items]) =>
                            items && items.length > 0 ? (
                                <div key={type} className="entity-group">
                                    <strong className="entity-type">
                                        {type.charAt(0).toUpperCase() + type.slice(1)}:
                                    </strong>
                                    <span className="entity-items">{items.join(', ')}</span>
                                </div>
                            ) : null
                        )}
                    </div>
                </div>
            )}

            {/* Advanced AI Features Section */}
            <div className="analysis-section">
                <div className="section-header">
                    <FaLightbulb className="section-icon" />
                    <h3>Advanced AI Features</h3>
                    <button
                        className="btn-toggle"
                        onClick={() => setShowAdvancedFeatures(!showAdvancedFeatures)}
                    >
                        {showAdvancedFeatures ? 'Hide' : 'Show'}
                    </button>
                </div>

                {showAdvancedFeatures && (
                    <div className="section-content">
                        {/* Custom Summary Generator */}
                        <div className="feature-box">
                            <h4>📝 Generate Custom Summary</h4>
                            <p className="feature-description">
                                Create a summary with your preferred length
                            </p>
                            <div className="feature-controls">
                                <select
                                    value={summaryLength}
                                    onChange={(e) => setSummaryLength(e.target.value)}
                                    className="feature-select"
                                    disabled={isGeneratingSummary}
                                >
                                    <option value="short">Short (1-2 sentences)</option>
                                    <option value="medium">Medium (1 paragraph)</option>
                                    <option value="long">Long (2-3 paragraphs)</option>
                                </select>
                                <button
                                    className="btn-primary"
                                    onClick={handleGenerateCustomSummary}
                                    disabled={isGeneratingSummary}
                                >
                                    {isGeneratingSummary ? 'Generating...' : 'Generate'}
                                </button>
                            </div>
                            {customSummary && (
                                <div className="feature-result">
                                    <div className="feature-result-header">
                                        <strong>Custom Summary ({summaryLength}):</strong>
                                        <button
                                            className="btn-copy-small"
                                            onClick={() => handleCopyToClipboard(customSummary.summary)}
                                            title="Copy summary"
                                        >
                                            <FaCopy />
                                        </button>
                                    </div>
                                    <p>{customSummary.summary}</p>
                                </div>
                            )}
                        </div>

                        {/* Information Extractor */}
                        <div className="feature-box">
                            <h4>🔍 Extract Specific Information</h4>
                            <p className="feature-description">
                                Pull out specific types of information from the document
                            </p>
                            <div className="feature-controls">
                                <select
                                    value={extractionType}
                                    onChange={(e) => setExtractionType(e.target.value)}
                                    className="feature-select"
                                    disabled={isExtracting}
                                >
                                    <option value="dates">📅 Dates & Deadlines</option>
                                    <option value="names">👤 Names & People</option>
                                    <option value="numbers">🔢 Numbers & Statistics</option>
                                    <option value="emails">📧 Email Addresses</option>
                                </select>
                                <button
                                    className="btn-primary"
                                    onClick={handleExtractInfo}
                                    disabled={isExtracting}
                                >
                                    {isExtracting ? 'Extracting...' : 'Extract'}
                                </button>
                            </div>
                            {extractedInfo && (
                                <div className="feature-result">
                                    <div className="feature-result-header">
                                        <strong>Extracted {extractionType}:</strong>
                                        <button
                                            className="btn-copy-small"
                                            onClick={() => handleCopyToClipboard(extractedInfo.result)}
                                            title="Copy extracted info"
                                        >
                                            <FaCopy />
                                        </button>
                                    </div>
                                    <p style={{ whiteSpace: 'pre-wrap' }}>{extractedInfo.result}</p>
                                </div>
                            )}
                        </div>
                    </div>
                )}
            </div>

            {/* Email Notification Section */}
            <div className="analysis-section email-section">
                <div className="section-header">
                    <FaEnvelope className="section-icon" />
                    <h3>Send Analysis via Email</h3>
                </div>
                <div className="section-content">
                    <div className="email-input-container">
                        <input
                            type="email"
                            className="email-input"
                            placeholder="Enter email address"
                            value={emailInput}
                            onChange={(e) => setEmailInput(e.target.value)}
                            disabled={isSendingEmail}
                        />
                        <button
                            className="btn-primary"
                            onClick={handleSendEmail}
                            disabled={isSendingEmail || !emailInput}
                        >
                            {isSendingEmail ? 'Sending...' : 'Send Email'}
                        </button>
                    </div>
                </div>
            </div>

            {/* Comparison Modal */}
            <ComparisonModal
                isOpen={showComparisonModal}
                onClose={() => setShowComparisonModal(false)}
                currentAnalysisId={id}
            />
        </div>
    );
};

export default AnalysisDisplay;